# Runtime phases.
PHASE_IDLE      = 0  # waiting for user input
PHASE_RESEARCH  = 1  # Scrapers active, Mind ingesting connections
PHASE_PHYSICS   = 2  # Physics engine running
PHASE_STABLE    = 3  # Physics exited, graph finalized
PHASE_THINKING  = 4  # Thought processes
PHASE_SYNTHESIS = 5  # Synthesis processes

DEFAULT_MAP_PATH = "word_info_map.sqlite3"
MIN_MERGE_SIMILARITY = 0.84
MAX_MERGE_SIMILARITY = 0.97
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

# Shared-memory capacities and sizes.
MAX_AGENTS = 64000
MAX_CONNECTIONS = 80000
AGENT_POSITION_FLOATS = 6
FLOAT_BYTES = 4
AGENT_POSITION_RECORD_BYTES = AGENT_POSITION_FLOATS * FLOAT_BYTES
AGENT_SEMANTIC_SEED_SCALE = 420.0
AGENT_SPAWN_JITTER = 60.0
AGENT_NEAR_PARENT_WEIGHT = 0.15
CONNECTION_COUNT_BYTES = 4
REPORT_SHM_BYTES = 128 * 1024
COMMAND_SHM_BYTES = 2 * 1024
STATUS_SHM_BYTES = 1024

# Connection record layout.
CONNECTION_RECORD_SIZE = 40
CONNECTION_UTILITY_OFFSET = 12
SUBJECT_QUANT_EXACT_OFFSET = 16
SUBJECT_TENSE_EXACT_OFFSET = 20
SUBJECT_TRUTH_EXACT_OFFSET = 24
PREDICATE_QUANT_EXACT_OFFSET = 28
PREDICATE_TENSE_EXACT_OFFSET = 32
PREDICATE_TRUTH_EXACT_OFFSET = 36

# Worker counts.
SCRAPE_THREADS = 8
EXTRACTION_THREADS = 4
THINK_THREADS = 8

# Dashboard/runtime config.
DASHBOARD_PORT = 8000
DASHBOARD_HOST = "0.0.0.0"
DASHBOARD_URL = f"http://localhost:{DASHBOARD_PORT}"
MAX_UI_AGENTS = 2400
MAX_UI_BONDS = 3600
MAX_UI_CONNECTION_STATS = 12000
WEBSOCKET_REFRESH_SECONDS = 1.0 / 30.0

# Reporting/synthesis config.
RESULTS_DIR = "results"
OLLAMA_GENERATE_URL = "http://localhost:11434/api/generate"
SYNTHESIS_MODEL = "llama3.2:3b"
DEFAULT_OLLAMA_CONNECT_TIMEOUT = 5
DEFAULT_OLLAMA_READ_TIMEOUT = 300
SYNTHESIS_TARGET_MATCH_THRESHOLD = 0.34
SYNTHESIS_ARGUMENT_LIMIT = 3
SYNTHESIS_MAX_CHAIN_CLAUSES = 6
ARGUMENT_SOURCE_DIVERSITY_TARGET = 3
ARGUMENT_SOURCE_DIVERSITY_MIN_MULTIPLIER = 0.45

# Query expansion config.
TARGET_QUERY_LIMIT = 5
BRIDGE_QUERY_LIMIT = 5
TARGET_FOCUS_PHRASE_LIMIT = 5

# Scraping config.
SCRAPE_DEFAULT_LIMIT = 16
SCRAPE_REFINEMENT_ENABLED = True
SCRAPE_REFINEMENT_LIMIT = SCRAPE_DEFAULT_LIMIT
SCRAPE_REFINEMENT_OFFSET = SCRAPE_DEFAULT_LIMIT
SERPER_RESULT_TIMEOUT = 5
SERPER_PAGE_TIMEOUT = 3
MIN_EXTRACTABLE_BLOCK_CHARS = 80
MAX_CHARS_PER_BLOCK = 2400
EXTRACTION_BLOCK_LIMIT = 16
EXTRACTION_SENTENCE_LIMIT = 96
EXTRACTION_CLAUSE_LIMIT = 180
MAX_CONNECTIONS_PER_QUERY = 512

# Thought-process config.
TARGET_SEED_LIMIT = 8
GOAL_AGENT_LIMIT = 8
PATH_TARGET_MATCH_THRESHOLD = 0.34
MIN_SUCCESS_STEPS = 2
MAX_THOUGHT_HOPS = 12
THOUGHT_FALLBACK_COMPLETED_LIMIT = 160
MAX_CONTEXT_SAMPLES = 4
STARTING_SCORE = 100.0
ENDPOINT_CONTEXT_LIMIT = 24
THOUGHT_AGENTS_PER_WORKER = 8
ACTIVE_SUBGRAPH_CANDIDATE_MULTIPLIER = 4
ACTIVE_ANCHOR_PAIR_LIMIT = 4
ACTIVE_SUBGRAPH_CONTEXT_HOPS = 1

# Text filters used only to prevent pronoun/function-word nodes from becoming
# thought seeds or argument anchors.
STOPWORD_TOKENS = frozenset({
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "had",
    "has", "have", "i", "in", "is", "it", "its", "of", "on", "or", "our",
    "that", "the", "their", "them", "these", "they", "this", "those", "to",
    "was", "we", "were", "with", "you",
})
