# Runtime phases.
PHASE_IDLE      = 0  # waiting for user input
PHASE_RESEARCH  = 1  # Scrapers active, Mind ingesting connections
PHASE_PHYSICS   = 2  # Physics engine running
PHASE_STABLE    = 3  # Physics exited, graph finalized
PHASE_THINKING  = 4  # Thought processes
PHASE_SYNTHESIS = 5  # Synthesis processes

DEFAULT_VECTOR_DIM = 384
DEFAULT_MAP_PATH = "word_info_map.sqlite3"
MIN_MERGE_SIMILARITY = 0.84
MAX_MERGE_SIMILARITY = 0.97
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

# Shared-memory capacities and sizes.
MAX_AGENTS = 64000
MAX_CONNECTIONS = 80000
AGENT_POSITION_FLOATS = 6
FLOAT_BYTES = 4
AGENT_POSITION_RECORD_BYTES = AGENT_POSITION_FLOATS * FLOAT_BYTES
AGENT_SEMANTIC_SEED_SCALE = 420.0
AGENT_SPAWN_JITTER = 60.0
AGENT_NEAR_PARENT_WEIGHT = 0.15
CONNECTION_COUNT_BYTES = 4
REPORT_SHM_BYTES = 128 * 1024
COMMAND_SHM_BYTES = 2 * 1024
STATUS_SHM_BYTES = 1024

# Connection record layout.
CONNECTION_RECORD_SIZE = 40
CONNECTION_UTILITY_OFFSET = 12
SUBJECT_QUANT_EXACT_OFFSET = 16
SUBJECT_TENSE_EXACT_OFFSET = 20
SUBJECT_TRUTH_EXACT_OFFSET = 24
PREDICATE_QUANT_EXACT_OFFSET = 28
PREDICATE_TENSE_EXACT_OFFSET = 32
PREDICATE_TRUTH_EXACT_OFFSET = 36

# Worker counts.
SCRAPE_THREADS = 8
THINK_THREADS = 8

# Dashboard/runtime config.
DASHBOARD_PORT = 8000
DASHBOARD_HOST = "0.0.0.0"
DASHBOARD_URL = f"http://localhost:{DASHBOARD_PORT}"
MAX_UI_AGENTS = 2400
MAX_UI_BONDS = 0
MAX_UI_CONNECTION_STATS = 12000
WEBSOCKET_REFRESH_SECONDS = 1.0 / 30.0

# Reporting/synthesis config.
RESULTS_DIR = "results"
FINAL_ARGUMENT_LIMIT = 8
OLLAMA_GENERATE_URL = "http://localhost:11434/api/generate"
QUERY_EXPANSION_MODEL = "llama3.2:1b"
SYNTHESIS_MODEL = "llama3.2:3b"
DEFAULT_OLLAMA_CONNECT_TIMEOUT = 5
DEFAULT_OLLAMA_READ_TIMEOUT = 300
SYNTHESIS_TARGET_MATCH_THRESHOLD = 0.34
SYNTHESIS_MAX_CHAIN_CLAUSES = 6
ARGUMENT_SOURCE_DIVERSITY_TARGET = 3
ARGUMENT_SOURCE_DIVERSITY_MIN_MULTIPLIER = 0.45

# Query expansion config.
TARGET_QUERY_LIMIT = 5
BRIDGE_QUERY_LIMIT = 5
TARGET_FOCUS_PHRASE_LIMIT = 5
TARGET_QUERY_SHORT_COUNT = 3
TARGET_QUERY_EVIDENCE_COUNT = 2
BRIDGE_QUERY_COUNT = 5
TARGET_FOCUS_PHRASE_COUNT = 5
MAX_EXPANDED_QUERY_TOKENS = 4

# Scraping config.
SCRAPE_DEFAULT_LIMIT = 24
SERPER_SHARE = 0.75
NON_SERPER_ENGINE_SAMPLE_COUNT = 3
SERPER_OVERFETCH_MULTIPLIER = 1.15
SERPER_MAX_RESULTS = 32
SERPER_MIN_REQUESTED_RESULTS = 8
SERPER_FULL_PAGE_RESULTS = 8
SNIPPET_ONLY_BLOCK_CHARS = 50
SERPER_RESULT_TIMEOUT = 5
SERPER_PAGE_TIMEOUT = 3
MIN_EXTRACTABLE_BLOCK_CHARS = 80
MAX_CHARS_PER_BLOCK = 900
EXTRACTION_BLOCK_LIMIT = 16
EXTRACTION_SENTENCE_LIMIT = 48
EXTRACTION_CLAUSE_LIMIT = 180
MAX_CONNECTIONS_PER_QUERY = 140
NON_SERPER_MIN_PER_ENGINE_LIMIT = 3
NON_SERPER_FOLLOWUP_BATCH_SIZE = 2
DEFAULT_UNKNOWN_YEAR = 0

# Thought-process config.
INFO_VECTOR_CONNECTION_LIMIT = 12
TARGET_SEED_LIMIT = 24
GOAL_AGENT_LIMIT = 12
BOOTSTRAP_THOUGHT_ROUNDS = 24
SUCCESS_SIMILARITY_THRESHOLD = 0.42
PATH_TARGET_MATCH_THRESHOLD = 0.34
MIN_SUCCESS_STEPS = 2
MAX_THOUGHT_HOPS = 12
THOUGHT_SEMANTIC_CHECK_INTERVAL = 3
THOUGHT_FALLBACK_COMPLETED_LIMIT = 160
LOW_SCORE_THRESHOLD = 8.0
MAX_ADJACENT_SAMPLES = 2
MAX_CONTEXT_SAMPLES = 2
UTILITY_FLOOR = 0.25
STARTING_SCORE = 100.0
THOUGHT_UTILITY_PENALTY_RATE = 0.38
THOUGHT_MIN_STEP_SCORE_MULTIPLIER = 0.72
SPATIAL_PROGRESS_REWARD_RATE = 0.35
SPECIFIC_DETAIL_REWARD_RATE = 0.45
SPECIFIC_DETAIL_REWARD_SATURATION = 9.0
THOUGHT_CITED_FACT_WEIGHT = 2.5
THOUGHT_DESTINATION_CITED_FACT_WEIGHT = 1.5
THOUGHT_CITED_FACT_WEIGHT_CAP = 5.0
THOUGHT_TENSE_PREFERENCE_WEIGHT = 2.25
THOUGHT_TENSE_OPPOSITION_PENALTY = 0.55
ENDPOINT_CONTEXT_LIMIT = 24
THOUGHT_MIN_LEXICAL_SEED_SCORE = 0.30
THOUGHT_AGENTS_PER_WORKER = 80

# Text filters used only to prevent pronoun/function-word nodes from becoming
# thought seeds or argument anchors.
STOPWORD_TOKENS = frozenset({
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "had",
    "has", "have", "i", "in", "is", "it", "its", "of", "on", "or", "our",
    "that", "the", "their", "them", "these", "they", "this", "those", "to",
    "was", "we", "were", "with", "you",
})
